### ISSUE TITLE
这是什么原因

### ISSUE THREAD

**Issue by hydrogenbond001** [ZCB-endeavor/visual-slam#1]
<img width="362" alt="屏幕截图 2024-10-26 110145" src="https://github.com/user-attachments/assets/d0fbcfff-78f0-4740-9d06-b1d8fc4c3593">

**Comment by ZCB-endeavor** [comment]
我认为你的opencv版本应该不是3.4.0，这个项目中我使用的opencv3.4.0开发的，你可以尝试更换一下版本再进行编译试试

**Comment by ZCB-endeavor** [comment]
我认为应该是OpenCV版本问题，这个项目中我使用的OpenCV 3.4.1开发的，你可以尝试更换OpenCV版本为3.x.x再进行编译试试

**Comment by hydrogenbond001** [comment]
opencv3.4.1没有这个问题，能否提供下其他包的版本，因为fbow有问题了

**Comment by hydrogenbond001** [comment]
我之前跑orb-slam3时的库在这不行

**Comment by ZCB-endeavor** [comment]
我稍后会将FBoW上传到github，你可以获取并编译使用

**Comment by ZCB-endeavor** [comment]
FBoW库已经上传好了，你可以尝试编译一下

**Comment by ZCB-endeavor** [comment]
代码已经上传到FBoW仓库[https://github.com/ZCB-endeavor/FBoW](url)，你可以尝试编译一下看看还有什么问题

**Comment by hydrogenbond001** [comment]
这个没问题了，但g2又有问题了（笑哭
`g2o/types/sba/types_six_dof_expmap.h: 没有那个文件或目录
 #include <g2o/types/sba/types_six_dof_expmap.h>`

**Comment by ZCB-endeavor** [comment]
其余的库可以直接从官方仓库安装，我使用Ubuntu20.04环境使用的版本如下：
g2o使用的是20201223的版本，Eigen使用的3.3.7，Pangolin使用0.6，yaml-cpp使用0.6.3，CSparse使用apt安装，如sudo apt install libsuitesparse-dev
可供参考

**Comment by hydrogenbond001** [comment]
好的谢谢，已经在尝试了

**Comment by hydrogenbond001** [comment]
成功啦
